version: '3.4'
services:
  mysql:
    image: mysql/mysql-server:5.7
    expose: 
      - 3306
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=yiicms
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=yiicms
    volumes:
      - ./yiicms.sql:/docker-entrypoint-initdb.d/init.sql

  yiicms:
    image: sheng/yiicms:latest
    depends_on: 
      - mysql
    expose:
      - 80
    ports:
      - "80:80"
    extra_hosts:
      - dev.yiicms.com:127.0.0.1

   